name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Make pages
        run: |
          poetry install
          poetry run make -C doc html
          touch doc/_build/html/.nojekyll
      - name: Deploy to GitHub Pages
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          build_dir: doc/_build/html
          github_token: ${{ secrets.GITHUB_TOKEN }}
