name: Linting and testing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          architecture: x64
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: poetry install
      - name: Lint sources
        run: poetry run black --check .
      - name: Test sources
        run: poetry run pytest
